# -*- coding: utf-8 -*-
"""Aplikasi Web Deteksi Fraud (Streamlit)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwCKG_ZrBI0Djfcta4xwqeYLyekF6_yU
"""

# ============================================================================
# APLIKASI WEB DETEKSI FRAUD - STREAMLIT
# Dibuat oleh: [Nama Anda/Tim Anda]
# ============================================================================

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go
import time
import os

# ============================================================================
# KONFIGURASI HALAMAN & JUDUL
# ============================================================================

st.set_page_config(
    page_title="Dasbor Deteksi Fraud",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Judul Utama
st.markdown("""
<style>
    .title {
        text-align: center;
        color: #1a5f7a; /* Warna biru korporat */
    }
    .metric-label {
        font-size: 1.1em;
    }
</style>
""", unsafe_allow_html=True)

st.markdown('<h1 class="title">🛡️ Dasbor Deteksi Fraud Perbankan</h1>', unsafe_allow_html=True)
st.markdown("<h3 style='text-align: center; color: grey;'>Analisis Transaksi Real-Time dan Batch berbasis Machine Learning</h3>", unsafe_allow_html=True)
st.markdown("---")

# ============================================================================
# PEMUATAN MODEL (CACHING UNTUK PERFORMA)
# ============================================================================
# st.cache_resource: Memuat model HANYA SEKALI saat aplikasi dimulai
# Ini adalah kunci agar aplikasi cepat dan tidak memuat ulang model setiap kali ada interaksi

@st.cache_resource
def load_models_and_artifacts():
    """
    Memuat semua model, scaler, dan encoder yang diperlukan dari file .pkl.
    Fungsi ini di-cache oleh Streamlit.
    """
    print("Memuat artefak... (Hanya terjadi sekali)")
    artifacts = {}
    try:
        artifacts['dt_model'] = joblib.load('decision_tree_fraud_model.pkl')
        artifacts['rf_model'] = joblib.load('random_forest_fraud_model.pkl')
        artifacts['scaler'] = joblib.load('scaler.pkl')
        artifacts['le_type'] = joblib.load('label_encoder_type.pkl')
        artifacts['le_amount_cat'] = joblib.load('label_encoder_amount_cat.pkl')
        artifacts['feature_columns'] = joblib.load('feature_columns.pkl')
        artifacts['model_comparison'] = joblib.load('model_comparison.pkl')
        print("Semua artefak berhasil dimuat.")
    except FileNotFoundError as e:
        st.error(f"FATAL ERROR: File artefak tidak ditemukan: {e.filename}")
        st.error("Pastikan semua file .pkl berada di folder yang sama dengan app.py!")
        artifacts = None
    except Exception as e:
        st.error(f"Error saat memuat artefak: {e}")
        artifacts = None
    return artifacts

artifacts = load_models_and_artifacts()

if artifacts is None:
    st.stop()

# ============================================================================
# FUNGSI PREPROCESSING (INTI DARI APLIKASI)
# ============================================================================
# Ini adalah logika dari Section 10/13 di notebook Anda, diubah jadi fungsi

def preprocess_data(df, le_type, le_amount_cat, scaler, feature_columns):
    """
    Menerima DataFrame mentah dan melakukan preprocessing lengkap
    (Feature Engineering, Encoding, Scaling)
    """
    try:
        # 1. Pastikan kolom asli ada
        # KOREKSI: Rename kolom jika ada nama 'Org' (dari notebook DT)
        df = df.rename(columns={
            'oldbalanceOrg': 'oldbalanceOrig',
            'newbalanceOrg': 'newbalanceOrig',
        })

        required_raw_cols = ['type', 'amount', 'oldbalanceOrig', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']
        for col in required_raw_cols:
            if col not in df.columns:
                st.error(f"Kolom yang dibutuhkan '{col}' tidak ditemukan di file Anda.")
                return None

        # 2. Feature Engineering (SAMA PERSIS DENGAN NOTEBOOK)
        df['balance_change_orig'] = df['newbalanceOrig'] - df['oldbalanceOrig']
        df['balance_change_dest'] = df['newbalanceDest'] - df['oldbalanceDest']
        df['amount_category'] = pd.cut(df['amount'],
                                             bins=[0, 1000, 10000, 100000, float('inf')],
                                             labels=['small', 'medium', 'large', 'very_large'],
                                             right=False)
        df['orig_zero_after'] = (df['newbalanceOrig'] == 0).astype(int)
        df['dest_zero_before'] = (df['oldbalanceDest'] == 0).astype(int)
        df['error_balance_orig'] = df['oldbalanceOrig'] + df['amount'] - df['newbalanceOrig']
        df['error_balance_dest'] = df['oldbalanceDest'] + df['amount'] - df['newbalanceDest']

        # 3. Label Encoding
        # Gunakan 'handle_unknown='ignore'' untuk menangani kategori baru di data bank
        # Tapi lebih baik kita handle secara manual agar tidak error
        df['type_encoded'] = le_type.transform(df['type'])
        df['amount_category_encoded'] = le_amount_cat.transform(df['amount_category'])

        # 4. Pastikan urutan kolom sesuai
        df_processed = df[feature_columns]

        # 5. Scaling
        X_scaled = scaler.transform(df_processed)

        return X_scaled, df_processed

    except Exception as e:
        st.error(f"Error saat preprocessing data: {e}")
        st.warning("Pastikan nama kolom di file Anda (misal 'type', 'amount') sudah benar.")
        return None, None

# ============================================================================
# NAVIGASI (SIDEBAR)
# ============================================================================

st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman",
    ('🏠 Ringkasan & Performa Model', '🔍 Prediksi Real-Time (Interaktif)', '📂 Prediksi Batch (Unggah File)'),
    captions=("Lihat metrik performa model", "Tes satu transaksi secara manual", "Analisis file CSV, XLS, atau XLSX")
)

st.sidebar.markdown("---")
st.sidebar.info(
    "**Tentang Aplikasi Ini**\n\n"
    "Dasbor ini menggunakan model Machine Learning (Random Forest) "
    "yang dilatih pada 6.3 juta transaksi untuk mendeteksi fraud secara akurat.\n\n"
    "**Pengembang:**\n"
    "- Mahdi\n"
    "- Ibnu\n"
    "- Brian\n"
    "- Anya"
)

# ============================================================================
# HALAMAN 1: RINGKASAN & PERFORMA MODEL
# ============================================================================

if page == '🏠 Ringkasan & Performa Model':
    st.header("Ringkasan & Performa Model Final")
    st.write("Bagian ini menampilkan metrik performa **final** dari model yang telah dilatih (dievaluasi pada *test set*). Ini adalah bukti **akurat** dan **kredibel** dari kemampuan model.")

    comp_data = artifacts['model_comparison']
    dt_metrics = comp_data['decision_tree']
    rf_metrics = comp_data['random_forest']

    st.subheader("Perbandingan Model: Decision Tree vs Random Forest")

    col1, col2 = st.columns(2)

    with col1:
        st.info("**Decision Tree (Baseline)**")
        st.metric("Test F1-Score", f"{dt_metrics['test_f1']:.4f}")
        st.metric("Test Precision", f"{dt_metrics['test_precision']:.4f}")
        st.metric("Test Recall", f"{dt_metrics['test_recall']:.4f}")
        st.metric("Test Accuracy", f"{dt_metrics['test_accuracy']:.4f}")

    with col2:
        st.success("**Random Forest (Model Final)**")
        st.metric("Test F1-Score", f"{rf_metrics['test_f1']:.4f}")
        st.metric("Test Precision", f"{rf_metrics['test_precision']:.4f}")
        st.metric("Test Recall", f"{rf_metrics['test_recall']:.4f}")
        st.metric("Test Accuracy", f"{rf_metrics['test_accuracy']:.4f}")

    st.markdown("""
    **Kesimpulan:**
    Model **Random Forest** dipilih sebagai model final karena memiliki **F1-Score** dan **Precision** yang deutlich lebih tinggi.
    - **Precision Tinggi** sangat penting untuk bank, karena ini berarti **mengurangi jumlah alarm palsu (False Positives)**, sehingga tidak mengganggu nasabah yang melakukan transaksi sah.
    """)

# ============================================================================
# HALAMAN 2: PREDIKSI REAL-TIME (INTERAKTIF)
# ============================================================================

elif page == '🔍 Prediksi Real-Time (Interaktif)':
    st.header("Tes Model Interaktif (Prediksi Transaksi Tunggal)")
    st.write("Gunakan formulir ini untuk menyimulasikan satu transaksi dan melihat prediksi model secara real-time. Ini membuktikan **relevansi** model untuk penggunaan langsung oleh bank.")

    # Gunakan form untuk input
    with st.form(key='prediction_form'):
        st.subheader("Masukkan Detail Transaksi:")

        # Pisahkan layout
        col1, col2 = st.columns(2)

        with col1:
            type = st.selectbox("Tipe Transaksi", options=artifacts['le_type'].classes_, help="Pilih tipe transaksi. 'TRANSFER' dan 'CASH_OUT' adalah yang paling sering fraud.")
            amount = st.number_input("Jumlah (Amount)", min_value=0.0, value=100000.0, step=1000.0)

        with col2:
            model_choice = st.radio("Pilih Model untuk Prediksi",
                                    ("Random Forest (Direkomendasikan)", "Decision Tree"),
                                    horizontal=True)

        st.markdown("---")
        st.subheader("Detail Saldo:")
        col3, col4 = st.columns(2)

        with col3:
            oldbalanceOrig = st.number_input("Saldo Awal Pengirim (oldbalanceOrig)", min_value=0.0, value=5000000.0)
            newbalanceOrig = st.number_input("Saldo Akhir Pengirim (newbalanceOrig)", min_value=0.0, value=0.0)

        with col4:
            oldbalanceDest = st.number_input("Saldo Awal Penerima (oldbalanceDest)", min_value=0.0, value=0.0)
            newbalanceDest = st.number_input("Saldo Akhir Penerima (newbalanceDest)", min_value=0.0, value=0.0)

        submit_button = st.form_submit_button(label='🔮 Jalankan Prediksi', use_container_width=True)

    # Setelah form disubmit
    if submit_button:
        # 1. Siapkan data input
        transaction_data = {
            'type': type,
            'amount': amount,
            'oldbalanceOrig': oldbalanceOrig,
            'newbalanceOrig': newbalanceOrig,
            'oldbalanceDest': oldbalanceDest,
            'newbalanceDest': newbalanceDest
        }

        # 2. Ubah jadi DataFrame
        df_input = pd.DataFrame([transaction_data])

        # 3. Preprocessing
        X_scaled, _ = preprocess_data(df_input, artifacts['le_type'], artifacts['le_amount_cat'], artifacts['scaler'], artifacts['feature_columns'])

        if X_scaled is not None:
            # 4. Pilih model
            model_to_use = artifacts['rf_model'] if "Random Forest" in model_choice else artifacts['dt_model']

            # 5. Prediksi
            prediction = model_to_use.predict(X_scaled)[0]
            probability = model_to_use.predict_proba(X_scaled)[0][1] # Probabilitas Fraud

            # 6. Tampilkan Hasil (Indikator Actionable!)
            st.subheader("Hasil Prediksi:")
            if prediction == 1:
                st.error(f"🚨🚨 KASUS FRAUD TERDETEKSI 🚨🚨")
                st.metric(label="Tingkat Keyakinan (Probabilitas Fraud)", value=f"{probability:.2%}")
                st.warning("**Tindakan yang Direkomendasikan:** Segera blokir transaksi ini dan lakukan investigasi manual.")
            else:
                st.success(f"✅ Transaksi Terlihat Aman (Non-Fraud)")
                st.metric(label="Tingkat Keyakinan (Probabilitas Fraud)", value=f"{probability:.2%}")
                st.info("**Tindakan yang Direkomendasikan:** Lanjutkan transaksi. Pantau secara normal.")

            with st.expander("Lihat Data Input yang Diproses"):
                st.write(df_input)

# ============================================================================
# HALAMAN 3: PREDIKSI BATCH (UNGGAH FILE)
# ============================================================================

elif page == '📂 Prediksi Batch (Unggah File)':
    st.header("Analisis Batch (Unggah File .csv, .xls, .xlsx)")
    st.write("Unggah file transaksi harian atau mingguan untuk dianalisis oleh model. Ini adalah inti dari operasional bank.")

    # KOREKSI .xlsx: Tambahkan 'openpyxl' ke requirements.txt
    uploaded_file = st.file_uploader("Unggah file transaksi Anda",
                                     type=["csv", "xls", "xlsx"],
                                     help="Unggah file .csv, .xls, atau .xlsx yang berisi data transaksi.")

    model_choice_batch = st.radio("Pilih Model untuk Analisis Batch",
                                  ("Random Forest (Direkomendasikan)", "Decision Tree"),
                                  horizontal=True)

    if uploaded_file is not None:
        try:
            # Tampilkan loading spinner
            with st.spinner(f"Memuat dan memproses {uploaded_file.name}... Ini mungkin memakan waktu..."):

                # KOREKSI .xlsx: Logika untuk membaca file excel
                if uploaded_file.name.endswith('.csv'):
                    df_bank = pd.read_csv(uploaded_file)
                elif uploaded_file.name.endswith(('.xls', '.xlsx')):
                    # engine='openpyxl' diperlukan untuk file xlsx modern
                    df_bank = pd.read_excel(uploaded_file, engine='openpyxl')

                df_original = df_bank.copy() # Simpan salinan asli untuk output
                st.write(f"✅ Berhasil memuat {df_bank.shape[0]} transaksi dari {uploaded_file.name}")

                # 2. Preprocessing
                X_scaled, df_processed = preprocess_data(df_bank, artifacts['le_type'], artifacts['le_amount_cat'], artifacts['scaler'], artifacts['feature_columns'])

                if X_scaled is not None:
                    # 3. Pilih model
                    model_to_use = artifacts['rf_model'] if "Random Forest" in model_choice_batch else artifacts['dt_model']

                    # 4. Prediksi (ini bagian yang intensif)
                    predictions = model_to_use.predict(X_scaled)
                    probabilities = model_to_use.predict_proba(X_scaled)[:, 1] # Probabilitas Fraud

                    # 5. Siapkan hasil (Indikator Actionable!)
                    df_original['Prediksi Fraud'] = predictions
                    df_original['Probabilitas Fraud (%)'] = (probabilities * 100).round(2)

                    # Tentukan Peringkat Risiko
                    def get_risk_level(prob):
                        if prob > 90:
                            return 'Sangat Berisiko (High)'
                        elif prob > 50:
                            return 'Berisiko Sedang (Medium)'
                        else:
                            return 'Risiko Rendah (Low)'

                    df_original['Peringkat Risiko'] = df_original['Probabilitas Fraud (%)'].apply(get_risk_level)

                    # Filter hanya kasus yang relevan (Medium & High risk)
                    df_fraud = df_original[df_original['Prediksi Fraud'] == 1].sort_values(by='Probabilitas Fraud (%)', ascending=False)

                    # ==================================================
                    # TAMPILKAN INDIKATOR ACTIONABLE (UNTUK ANALIS BANK)
                    # ==================================================
                    st.success("🎉 Analisis Selesai!")
                    st.subheader("Ringkasan Eksekutif (Actionable Indicators)")
                    st.write("Ini adalah indikator yang paling penting untuk ditindaklanjuti oleh analis bank.")

                    total_fraud = len(df_fraud)
                    total_transactions = len(df_original)
                    fraud_rate = (total_fraud / total_transactions) * 100
                    potential_loss_detected = df_fraud['amount'].sum()

                    kpi_cols = st.columns(3)
                    kpi_cols[0].metric("Total Transaksi Terdeteksi Fraud", f"{total_fraud} Transaksi")
                    kpi_cols[1].metric("Tingkat Fraud di Batch Ini", f"{fraud_rate:.2f}%")
                    kpi_cols[2].metric("Total Potensi Kerugian Terdeteksi", f"Rp {potential_loss_detected:,.2f}")

                    st.markdown("---")

                    # Tampilkan Peringkat Risiko dan Daftar Aksi
                    col_chart, col_table = st.columns([1, 2])

                    with col_chart:
                        st.subheader("Distribusi Peringkat Risiko")
                        risk_counts = df_original[df_original['Prediksi Fraud'] == 1]['Peringkat Risiko'].value_counts()

                        if not risk_counts.empty:
                            fig = go.Figure(data=[go.Donut(
                                labels=risk_counts.index,
                                values=risk_counts.values,
                                hole=.4,
                                marker_colors=['#FF4B4B', '#FFB450'] # Warna merah dan kuning
                            )])
                            fig.update_layout(title='Peringkat Risiko (Kasus Fraud)', margin=dict(t=30, b=0, l=0, r=0))
                            st.plotly_chart(fig, use_container_width=True)
                        else:
                            st.success("Tidak ada fraud berisiko tinggi/sedang yang terdeteksi.")

                    with col_table:
                        st.subheader("Daftar Aksi (Prioritas Investigasi)")
                        st.write("Daftar transaksi yang harus segera diinvestigasi (diurutkan berdasarkan probabilitas tertinggi).")

                        # Tampilkan hanya kolom yang relevan untuk analis
                        cols_to_show = ['Peringkat Risiko', 'Probabilitas Fraud (%)', 'amount', 'type', 'oldbalanceOrig', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']
                        # Pastikan kolom ada sebelum menampilkannya
                        cols_exist = [col for col in cols_to_show if col in df_fraud.columns]

                        st.dataframe(df_fraud[cols_exist], height=300)

                        # Tombol Download
                        csv_output = df_fraud[cols_exist].to_csv(index=False).encode('utf-8')
                        st.download_button(
                            label="📥 Unduh Daftar Aksi (.csv)",
                            data=csv_output,
                            file_name="daftar_investigasi_fraud.csv",
                            mime="text/csv"
                        )

                    st.markdown("---")
                    with st.expander("Lihat Semua Transaksi (Data Asli + Prediksi)"):
                        st.dataframe(df_original)

        except Exception as e:
            st.error(f"Gagal memproses file: {e}")
            st.warning("Pastikan file Anda adalah file CSV, XLS, atau XLSX yang valid dan memiliki kolom yang benar.")