# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nu3clMpMCKOlm8SgZx3aw_xy7dGU6Cna
"""

# ============================================================================
# APLIKASI WEB DETEKSI FRAUD v2.1 - PERBAIKAN FINAL
# ============================================================================

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go
import time
import os

# ============================================================================
# KONFIGURASI HALAMAN & JUDUL
# ============================================================================

st.set_page_config(
    page_title="Dasbor Deteksi Fraud (v2.1)",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ... (CSS dan Judul tetap sama) ...
st.markdown("""
<style>
    .title { text-align: center; color: #1a5f7a; }
    .metric-label { font-size: 1.1em; }
</style>
""", unsafe_allow_html=True)
st.markdown('<h1 class="title">🛡️ Dasbor Deteksi Fraud Perbankan</h1>', unsafe_allow_html=True)
st.markdown("<h3 style='text-align: center; color: grey;'>Analisis Transaksi Real-Time dan Batch berbasis Machine Learning</h3>", unsafe_allow_html=True)
st.markdown("---")

# ============================================================================
# PEMUATAN MODEL (CACHING UNTUK PERFORMA)
# ============================================================================

@st.cache_resource
def load_models_and_artifacts():
    print("Memuat artefak... (Hanya terjadi sekali)")
    artifacts = {}
    try:
        # Daftar file pkl yang WAJIB ada
        required_files = [
            'decision_tree_fraud_model.pkl', 'random_forest_fraud_model.pkl',
            'scaler.pkl', 'label_encoder_type.pkl', 'label_encoder_amount_cat.pkl',
            'feature_columns.pkl', 'model_comparison.pkl', 'model_info.pkl',
            'random_forest_model_info.pkl'
        ]

        # Cek ketersediaan file sebelum memuat
        for f in required_files:
            if not os.path.exists(f):
                st.error(f"FATAL ERROR: File artefak tidak ditemukan: {f}")
                st.error("Pastikan semua file .pkl ada di repository GitHub Anda.")
                return None

        artifacts['dt_model'] = joblib.load('decision_tree_fraud_model.pkl')
        artifacts['rf_model'] = joblib.load('random_forest_fraud_model.pkl')
        artifacts['scaler'] = joblib.load('scaler.pkl')
        artifacts['le_type'] = joblib.load('label_encoder_type.pkl')
        artifacts['le_amount_cat'] = joblib.load('label_encoder_amount_cat.pkl')
        artifacts['feature_columns'] = joblib.load('feature_columns.pkl')
        artifacts['model_comparison'] = joblib.load('model_comparison.pkl')
        print("Semua artefak berhasil dimuat.")
    except Exception as e:
        st.error(f"Error saat memuat artefak: {e}")
        artifacts = None
    return artifacts

artifacts = load_models_and_artifacts()

if artifacts is None:
    st.error("Aplikasi tidak dapat dimulai karena artefak model gagal dimuat. Harap periksa log.")
    st.stop()

# ============================================================================
# FUNGSI PREPROCESSING
# ============================================================================

def preprocess_data_form(df, le_type, le_amount_cat, scaler, feature_columns):
    """
    Preprocessing untuk FORM real-time (Halaman 2).
    Kolom sudah pasti benar (dari st.form).
    """
    try:
        df_copy = df.copy()
        # 1. Feature Engineering
        df_copy['balance_change_orig'] = df_copy['newbalanceOrig'] - df_copy['oldbalanceOrig']
        df_copy['balance_change_dest'] = df_copy['newbalanceDest'] - df_copy['oldbalanceDest']
        df_copy['amount_category'] = pd.cut(df_copy['amount'],
                                             bins=[0, 1000, 10000, 100000, float('inf')],
                                             labels=['small', 'medium', 'large', 'very_large'],
                                             right=False)
        df_copy['orig_zero_after'] = (df_copy['newbalanceOrig'] == 0).astype(int)
        df_copy['dest_zero_before'] = (df_copy['oldbalanceDest'] == 0).astype(int)
        df_copy['error_balance_orig'] = df_copy['oldbalanceOrig'] + df_copy['amount'] - df_copy['newbalanceOrig']
        df_copy['error_balance_dest'] = df_copy['oldbalanceDest'] + df_copy['amount'] - df_copy['newbalanceDest']

        # 3. Label Encoding
        df_copy['type_encoded'] = le_type.transform(df_copy['type'])
        df_copy['amount_category_encoded'] = le_amount_cat.transform(df_copy['amount_category'])

        # 4. Pastikan urutan kolom sesuai
        df_processed = df_copy[feature_columns]

        # 5. Scaling
        X_scaled = scaler.transform(df_processed)

        return X_scaled, df_copy

    except Exception as e:
        st.error(f"Error saat preprocessing data form: {e}")
        return None, None

def preprocess_data_mapped(df_mapped, le_type, le_amount_cat, scaler, feature_columns):
    """
    Preprocessing untuk file BATCH yang sudah dipetakan (Halaman 3).
    Ini menangani tipe yang tidak dikenal.
    """
    try:
        df = df_mapped.copy()
        # 1. Feature Engineering (SAMA PERSIS DENGAN NOTEBOOK)
        df['balance_change_orig'] = df['newbalanceOrig'] - df['oldbalanceOrig']
        df['balance_change_dest'] = df['newbalanceDest'] - df['oldbalanceDest']
        df['amount_category'] = pd.cut(df['amount'],
                                             bins=[0, 1000, 10000, 100000, float('inf')],
                                             labels=['small', 'medium', 'large', 'very_large'],
                                             right=False)
        df['orig_zero_after'] = (df['newbalanceOrig'] == 0).astype(int)
        df['dest_zero_before'] = (df['oldbalanceDest'] == 0).astype(int)
        df['error_balance_orig'] = df['oldbalanceOrig'] + df['amount'] - df['newbalanceOrig']
        df['error_balance_dest'] = df['oldbalanceDest'] + df['amount'] - df['newbalanceDest']

        # 3. Label Encoding (Handling Tipe Tidak Dikenal)
        known_types = le_type.classes_
        unknown_types = set(df['type']) - set(known_types)

        if len(unknown_types) > 0:
            st.warning(f"Ditemukan Tipe Transaksi baru yang tidak dikenal: {unknown_types}")
            most_common_type = 'PAYMENT' # Asumsi
            df['type'] = df['type'].apply(lambda x: most_common_type if x in unknown_types else x)

        df['type_encoded'] = le_type.transform(df['type'])
        df['amount_category_encoded'] = le_amount_cat.transform(df['amount_category'])

        # 4. Pastikan urutan kolom sesuai
        df_processed = df[feature_columns]

        # 5. Scaling
        X_scaled = scaler.transform(df_processed)

        return X_scaled, df

    except Exception as e:
        st.error(f"Error saat preprocessing data batch: {e}")
        st.warning("Pastikan pemetaan kolom Anda sudah benar.")
        return None, None

# ============================================================================
# NAVIGASI (SIDEBAR)
# ============================================================================

st.sidebar.title("Navigasi")
page = st.sidebar.radio("Pilih Halaman",
    ('🏠 Ringkasan & Performa Model', '🔍 Prediksi Real-Time (Interaktif)', '📂 Prediksi Batch (Unggah File)'),
    captions=("Lihat metrik performa model", "Tes satu transaksi secara manual", "Analisis file CSV, XLS, atau XLSX")
)
st.sidebar.markdown("---")
st.sidebar.info(
    "**Tentang Aplikasi Ini (v2.1)**\n\n"
    "Dasbor ini menggunakan model Machine Learning (Random Forest) "
    "dan fitur Pemetaan Kolom untuk data bank yang fleksibel.\n\n"
    "**Pengembang:**\n"
    "- Mahdi"
    "- Ibnu"
    "- Brian"
    "- Anya"
)
# ============================================================================
# HALAMAN 1: RINGKASAN & PERFORMA MODEL
# ============================================================================

if page == '🏠 Ringkasan & Performa Model':
    st.header("Ringkasan & Performa Model Final")
    st.write("Bagian ini menampilkan metrik performa **final** dari model yang telah dilatih (dievaluasi pada *test set*). Ini adalah bukti **akurat** dan **kredibel** dari kemampuan model.")

    comp_data = artifacts['model_comparison']

    # Gunakan .get() untuk keamanan jika file pkl lama
    dt_metrics = comp_data.get('decision_tree', {})
    rf_metrics = comp_data.get('random_forest', {})

    st.subheader("Perbandingan Model: Decision Tree vs Random Forest")
    col1, col2 = st.columns(2)
    with col1:
        st.info("**Decision Tree (Baseline)**")
        st.metric("Test F1-Score", f"{dt_metrics.get('test_f1', 0):.4f}")
        st.metric("Test Precision", f"{dt_metrics.get('test_precision', 0):.4f}")
        st.metric("Test Recall", f"{dt_metrics.get('test_recall', 0):.4f}")
    with col2:
        st.success("**Random Forest (Model Final)**")
        st.metric("Test F1-Score", f"{rf_metrics.get('test_f1', 0):.4f}")
        st.metric("Test Precision", f"{rf_metrics.get('test_precision', 0):.4f}")
        st.metric("Test Recall", f"{rf_metrics.get('test_recall', 0):.4f}")

    st.markdown("""
    **Kesimpulan:**
    Model **Random Forest** dipilih sebagai model final karena memiliki **F1-Score** dan **Precision** yang deutlich lebih tinggi,
    menunjukkan keseimbangan yang lebih baik dan lebih sedikit *false positive* dibandingkan Decision Tree.
    """)

# ============================================================================
# HALAMAN 2: PREDIKSI REAL-TIME (INTERAKTIF) - PERBAIKAN
# ============================================================================

elif page == '🔍 Prediksi Real-Time (Interaktif)':

    st.header("Tes Model Interaktif (Prediksi Transaksi Tunggal)")
    st.write("Gunakan formulir ini untuk menyimulasikan satu transaksi dan melihat prediksi model secara real-time.")

    with st.form(key='prediction_form'):
        st.subheader("Masukkan Detail Transaksi:")
        col1, col2 = st.columns(2)

        with col1:
            type = st.selectbox("Tipe Transaksi", options=artifacts['le_type'].classes_, help="Pilih 'TRANSFER' atau 'CASH_OUT' untuk tes fraud.")
            amount = st.number_input("Jumlah (Amount)", min_value=0.0, value=100000.0)
        with col2:
            model_choice = st.radio("Pilih Model", ("Random Forest (Direkomendasikan)", "Decision Tree"), horizontal=True)

        st.subheader("Detail Saldo:")
        st.markdown(
            "**Data Tes Fraud (Contoh):** Tipe: `TRANSFER`, Amount: `1000000`, Saldo Awal Pengirim: `1000000`, "
            "Saldo Akhir Pengirim: `0`, Saldo Awal Penerima: `0`, Saldo Akhir Penerima: `0`"
        )
        col3, col4 = st.columns(2)

        with col3:
            oldbalanceOrig = st.number_input("Saldo Awal Pengirim (oldbalanceOrig)", min_value=0.0, value=5000000.0)
            newbalanceOrig = st.number_input("Saldo Akhir Pengirim (newbalanceOrig)", min_value=0.0, value=0.0)
        with col4:
            oldbalanceDest = st.number_input("Saldo Awal Penerima (oldbalanceDest)", min_value=0.0, value=0.0)
            newbalanceDest = st.number_input("Saldo Akhir Penerima (newbalanceDest)", min_value=0.0, value=0.0)

        submit_button = st.form_submit_button(label='🔮 Jalankan Prediksi', use_container_width=True)

    # ===== PERBAIKAN: Logika ini sekarang MENJALANKAN MODEL =====
    if submit_button:
        # 1. Siapkan data input
        transaction_data = {
            'type': type,
            'amount': amount,
            'oldbalanceOrig': oldbalanceOrig,
            'newbalanceOrig': newbalanceOrig,
            'oldbalanceDest': oldbalanceDest,
            'newbalanceDest': newbalanceDest
        }

        # 2. Ubah jadi DataFrame
        df_input = pd.DataFrame([transaction_data])

        with st.spinner("Menganalisis transaksi..."):
            # 3. Preprocessing (Gunakan fungsi form baru)
            X_scaled, df_processed_input = preprocess_data_form(
                df_input,
                artifacts['le_type'],
                artifacts['le_amount_cat'],
                artifacts['scaler'],
                artifacts['feature_columns']
            )

            if X_scaled is not None:
                # 4. Pilih model
                model_to_use = artifacts['rf_model'] if "Random Forest" in model_choice else artifacts['dt_model']
                model_name = "Random Forest" if "Random Forest" in model_choice else "Decision Tree"

                # 5. Prediksi
                prediction = model_to_use.predict(X_scaled)[0]
                probability = model_to_use.predict_proba(X_scaled)[0][1] # Probabilitas Fraud

                # 6. Tampilkan Hasil (Indikator Actionable!)
                st.subheader(f"Hasil Prediksi (Model: {model_name}):")
                if prediction == 1:
                    st.error(f"🚨🚨 KASUS FRAUD TERDETEKSI 🚨🚨")
                    st.metric(label="Tingkat Keyakinan (Probabilitas Fraud)", value=f"{probability:.2%}")
                    st.warning("**Tindakan yang Direkomendasikan:** Segera blokir transaksi ini dan lakukan investigasi manual.")
                else:
                    st.success(f"✅ Transaksi Terlihat Aman (Non-Fraud)")
                    st.metric(label="Tingkat Keyakinan (Probabilitas Fraud)", value=f"{probability:.2%}")
                    st.info("**Tindakan yang Direkomendasikan:** Lanjutkan transaksi. Pantau secara normal.")

                with st.expander("Lihat Data Input yang Diproses (Termasuk Fitur Rekayasa)"):
                    st.dataframe(df_processed_input)
            else:
                st.error("Gagal memproses data input.")

# ============================================================================
# HALAMAN 3: PREDIKSI BATCH (UNGGAH FILE)
# ============================================================================

elif page == '📂 Prediksi Batch (Unggah File)':
    st.header("Analisis Batch (Unggah File .csv, .xls, .xlsx)")
    st.write("Unggah file transaksi harian atau mingguan. Aplikasi ini akan memandu Anda memetakan kolom jika namanya berbeda.")

    # ... (Logika Halaman 3 tetap sama, sudah solid) ...
    uploaded_file = st.file_uploader("1. Unggah file transaksi Anda",
                                     type=["csv", "xls", "xlsx"],
                                     help="Unggah file .csv, .xls, atau .xlsx.")

    if uploaded_file is not None:
        try:
            # Baca file
            if uploaded_file.name.endswith('.csv'):
                df_bank = pd.read_csv(uploaded_file)
            elif uploaded_file.name.endswith(('.xls', '.xlsx')):
                df_bank = pd.read_excel(uploaded_file, engine='openpyxl')

            st.success(f"✅ Berhasil memuat {df_bank.shape[0]} transaksi dari {uploaded_file.name}")
            st.session_state['df_bank'] = df_bank
        except Exception as e:
            st.error(f"Gagal memuat file: {e}")
            if 'df_bank' in st.session_state:
                del st.session_state['df_bank']

    if 'df_bank' in st.session_state:
        df_bank = st.session_state['df_bank']

        st.markdown("---")
        st.subheader("2. Pemetaan Kolom")
        st.write("Model kami membutuhkan kolom-kolom tertentu. Tolong 'petakan' kolom dari file Anda ke kolom yang dibutuhkan model.")

        required_model_columns = {
            'type': 'Tipe transaksi (misal: TRANSFER, PAYMENT)',
            'amount': 'Jumlah uang yang ditransfer',
            'oldbalanceOrig': 'Saldo awal pengirim',
            'newbalanceOrig': 'Saldo akhir pengirim',
            'oldbalanceDest': 'Saldo awal penerima',
            'newbalanceDest': 'Saldo akhir penerima'
        }

        uploaded_file_columns = df_bank.columns.tolist()

        with st.form(key='column_mapping_form'):
            mapping_dict = {}
            cols = st.columns(2)

            for i, (col_name, description) in enumerate(required_model_columns.items()):
                with cols[i % 2]:
                    st.markdown(f"**{col_name}**")
                    st.caption(description)
                    try:
                        default_index = [c.lower() for c in uploaded_file_columns].index(col_name.lower())
                    except ValueError:
                        default_index = 0

                    selected_col = st.selectbox(
                        f"Pilih kolom dari file Anda untuk '{col_name}'",
                        options=uploaded_file_columns,
                        index=default_index,
                        key=f"map_{col_name}"
                    )
                    mapping_dict[col_name] = selected_col

            st.markdown("---")
            model_choice_batch = st.radio("3. Pilih Model untuk Analisis Batch",
                                          ("Random Forest (Direkomendasikan)", "Decision Tree"),
                                          horizontal=True)

            process_button = st.form_submit_button(label='🚀 4. Proses dan Analisis Data', use_container_width=True)

        if process_button:
            with st.spinner("Memproses dan menganalisis data..."):

                try:
                    df_mapped = df_bank[list(mapping_dict.values())].copy()
                    df_mapped.columns = list(mapping_dict.keys())
                    st.write("✅ Pemetaan kolom berhasil.")
                except Exception as e:
                    st.error(f"Error saat memetakan kolom: {e}")
                    st.stop()

                X_scaled, df_processed_output = preprocess_data_mapped(
                    df_mapped,
                    artifacts['le_type'],
                    artifacts['le_amount_cat'],
                    artifacts['scaler'],
                    artifacts['feature_columns']
                )

                if X_scaled is not None:
                    model_to_use = artifacts['rf_model'] if "Random Forest" in model_choice_batch else artifacts['dt_model']

                    predictions = model_to_use.predict(X_scaled)
                    probabilities = model_to_use.predict_proba(X_scaled)[:, 1]

                    df_original_output = df_bank.copy()
                    df_original_output['Prediksi Fraud'] = predictions
                    df_original_output['Probabilitas Fraud (%)'] = (probabilities * 100).round(2)

                    def get_risk_level(prob):
                        if prob > 90: return 'Sangat Berisiko (High)'
                        elif prob > 50: return 'Berisiko Sedang (Medium)'
                        else: return 'Risiko Rendah (Low)'

                    df_original_output['Peringkat Risiko'] = df_original_output['Probabilitas Fraud (%)'].apply(get_risk_level)

                    df_fraud = df_original_output[df_original_output['Prediksi Fraud'] == 1].sort_values(by='Probabilitas Fraud (%)', ascending=False)

                    st.success("🎉 Analisis Selesai!")
                    st.subheader("Ringkasan Eksekutif (Actionable Indicators)")

                    total_fraud = len(df_fraud)
                    total_transactions = len(df_original_output)
                    fraud_rate = (total_fraud / total_transactions) * 100 if total_transactions > 0 else 0
                    potential_loss_detected = df_original_output.loc[df_original_output['Prediksi Fraud'] == 1, mapping_dict['amount']].sum()

                    kpi_cols = st.columns(3)
                    kpi_cols[0].metric("Total Transaksi Terdeteksi Fraud", f"{total_fraud} Transaksi")
                    kpi_cols[1].metric("Tingkat Fraud di Batch Ini", f"{fraud_rate:.2f}%")
                    kpi_cols[2].metric("Total Potensi Kerugian Terdeteksi", f"Rp {potential_loss_detected:,.2f}")

                    st.markdown("---")

                    col_chart, col_table = st.columns([1, 2])

                    with col_chart:
                        st.subheader("Distribusi Peringkat Risiko")
                        risk_counts = df_original_output[df_original_output['Prediksi Fraud'] == 1]['Peringkat Risiko'].value_counts()
                        if not risk_counts.empty:
                            fig = go.Figure(data=[go.Donut(labels=risk_counts.index, values=risk_counts.values, hole=.4, marker_colors=['#FF4B4B', '#FFB450'])])
                            fig.update_layout(title='Peringkat Risiko (Kasus Fraud)', margin=dict(t=30, b=0, l=0, r=0))
                            st.plotly_chart(fig, use_container_width=True)
                        else:
                            st.success("Tidak ada fraud berisiko tinggi/sedang yang terdeteksi.")

                    with col_table:
                        st.subheader("Daftar Aksi (Prioritas Investigasi)")
                        st.write("Daftar transaksi yang harus segera diinvestigasi.")

                        cols_to_show = ['Peringkat Risiko', 'Probabilitas Fraud (%)'] + list(mapping_dict.values())
                        st.dataframe(df_fraud[cols_to_show], height=300)

                        csv_output = df_fraud[cols_to_show].to_csv(index=False).encode('utf-8')
                        st.download_button(
                            label="📥 Unduh Daftar Aksi (.csv)",
                            data=csv_output,
                            file_name="daftar_investigasi_fraud.csv",
                            mime="text/csv"
                        )

                    st.markdown("---")
                    with st.expander("Lihat Semua Transaksi (Data Asli + Prediksi)"):
                        st.dataframe(df_original_output)